Bug Fixes, Added RPS and Config
hackarmour/discord-assistant pull request #67
Opened 2021-08-04 11:12 UTC by TheEmperor342

## Changlog
- + Added Rock-Paper-Scissors
- + Added Configuration Cog
- + Updated Help
- + Fixed all link related errors in `f` command
- - Removed `memes` command

btw the `Configuration/Leveling.json` is intentional here

2021-08-05 11:41 UTC, itsmebirdie commented
Acknowledged.

2021-08-05 11:45 UTC, itsmebirdie commented on Cogs/Fun.py
> +            if any(k in reason for k in ["https://", "http://", "discord.com", "discord.gg"]):
I would recommend returning an error like:
`There's a Discord invite link in the reason` when having `discord.gg` or `discord.com/invite` in the reason

2021-08-05 11:51 UTC, itsmebirdie commented on Cogs/Fun.py
> +                continue
Please may I ask an explanation of what it does? 😄

2021-08-05 11:57 UTC, itsmebirdie reviewed
Review done.
Awaiting testing.

In the meantime please take a look at the comments 😄

2021-08-05 11:59 UTC, itsmebirdie commented on Dockerfile
> +RUN pip install discord.py[voice] requests dpymenus youtube_dl disrank numpy pandas discord-components
Hey, this was already committed I guess..

2021-08-05 12:04 UTC, itsmebirdie requested changes
Testing failed.

![image](https://user-images.githubusercontent.com/63333626/128346773-00afb605-bc39-4ef2-897c-a4a3414958fb.png)
![image](https://user-images.githubusercontent.com/63333626/128346791-b0745066-d5ed-43d7-b06d-509f03728a9e.png)

2021-08-05 12:04 UTC, TheEmperor342 commented on Dockerfile
> +RUN pip install discord.py[voice] requests dpymenus youtube_dl disrank numpy pandas discord-components
I haven't even touched this file though

2021-08-05 12:06 UTC, TheEmperor342 commented on Cogs/Fun.py
> +                continue
In the json from the request of the api there is a key called `nsfw` which is `True` if the image is nsfw

if it is true,
the while True loop is continued 

if it is not the image is sent as an embed and the loop is broken

2021-08-05 12:07 UTC, itsmebirdie requested changes
The bot is randomly throwing errors
![image](https://user-images.githubusercontent.com/63333626/128347213-8e147ab6-a94a-49a5-a355-881496dfad58.png)
![image](https://user-images.githubusercontent.com/63333626/128347217-63b85fb1-c670-43b1-a6a9-ceda924c6c8e.png)

2021-08-06 12:10 UTC, itsmebirdie commented
Acknowledged commits.

2021-08-06 12:11 UTC, itsmebirdie reviewed
Code review done.
Awaiting testing.

2021-08-06 12:19 UTC, itsmebirdie requested changes
Testing failed.
Fix requested for:
![image](https://user-images.githubusercontent.com/63333626/128509240-4ca6a4b8-6bfb-400a-8be9-6caebdf83f4f.png)


when specifying a help category it shows the default help menu instead of the specific category help.

2021-08-06 12:23 UTC, itsmebirdie commented
Also the bot is being rate limited when adding all the reactions in `ttt`
It is better to use the new buttons instead of reactions

2021-08-07 01:39 UTC, TheEmperor342 commented
> Testing failed.
> Fix requested for:
> ![image](https://user-images.githubusercontent.com/63333626/128509240-4ca6a4b8-6bfb-400a-8be9-6caebdf83f4f.png)
> 
> when specifying a help category it shows the default help menu instead of the specific category help.

That is intentional. Choose what you want from the select

2021-08-07 01:40 UTC, TheEmperor342 commented
> Testing failed.
> Fix requested for:
> ![image](https://user-images.githubusercontent.com/63333626/128509240-4ca6a4b8-6bfb-400a-8be9-6caebdf83f4f.png)
> 
> when specifying a help category it shows the default help menu instead of the specific category help.

Okay

2021-08-08 13:33 UTC, itsmebirdie approved these changes
Approved for merge.
Good Job!

2021-08-08 13:33 UTC, merged